export enum LOG_LEVEL {
  LOG_FATAL = 0,
  LOG_ERROR = 1,
  LOG_WARN = 2,
  LOG_INFO = 3,
  LOG_DEBUG = 4,
  LOG_BUFF = 5
}

// spell-checker: disable
export enum NET_SDK_ERROR {
  NET_SDK_SUCCESS = 0,
  NET_SDK_PASSWORD_ERROR = 1,
  NET_SDK_NOENOUGH_AUTH = 2,
  NET_SDK_NOINIT = 3,
  NET_SDK_CHANNEL_ERROR = 4,
  NET_SDK_OVER_MAXLINK = 5,
  NET_SDK_LOGIN_REFUSED = 6,
  NET_SDK_VERSION_NOMATCH = 7,
  NET_SDK_NETWORK_FAIL_CONNECT = 8,
  NET_SDK_NETWORK_NOT_CONNECT = 9,
  NET_SDK_NETWORK_SEND_ERROR = 10,
  NET_SDK_NETWORK_RECV_ERROR = 11,
  NET_SDK_NETWORK_RECV_TIMEOUT = 12,
  NET_SDK_NETWORK_ERRORDATA = 13,
  NET_SDK_ORDER_ERROR = 14,
  NET_SDK_OPER_BY_OTHER = 15,
  NET_SDK_OPER_NOPERMIT = 16,
  NET_SDK_COMMAND_TIMEOUT = 17,
  NET_SDK_ERROR_SERIALPORT = 18,
  NET_SDK_ERROR_ALARMPORT = 19,
  NET_SDK_PARAMETER_ERROR = 20,
  NET_SDK_CHAN_EXCEPTION = 21,
  NET_SDK_NODISK = 22,
  NET_SDK_ERROR_DISKNUM = 23,
  NET_SDK_DISK_FULL = 24,
  NET_SDK_DISK_ERROR = 25,
  NET_SDK_NOSUPPORT = 26,
  NET_SDK_BUSY = 27,
  NET_SDK_MODIFY_FAIL = 28,
  NET_SDK_PASSWORD_FORMAT_ERROR = 29,
  NET_SDK_DISK_FORMATING = 30,
  NET_SDK_DVR_NORESOURCE = 31,
  NET_SDK_DVR_OPRATE_FAILED = 32,
  NET_SDK_OPEN_HOSTSOUND_FAIL = 33,
  NET_SDK_DVR_VOICEOPENED = 34,
  NET_SDK_TIME_INPUTERROR = 35,
  NET_SDK_NOSPECFILE = 36,
  NET_SDK_CREATEFILE_ERROR = 37,
  NET_SDK_FILEOPENFAIL = 38,
  NET_SDK_OPERNOTFINISH = 39,
  NET_SDK_GETPLAYTIMEFAIL = 40,
  NET_SDK_PLAYFAIL = 41,
  NET_SDK_FILEFORMAT_ERROR = 42,
  NET_SDK_DIR_ERROR = 43,
  NET_SDK_ALLOC_RESOURCE_ERROR = 44,
  NET_SDK_AUDIO_MODE_ERROR = 45,
  NET_SDK_NOENOUGH_BUF = 46,
  NET_SDK_CREATESOCKET_ERROR = 47,
  NET_SDK_SETSOCKET_ERROR = 48,
  NET_SDK_MAX_NUM = 49,
  NET_SDK_USERNOTEXIST = 50,
  NET_SDK_WRITEFLASHERROR = 51,
  NET_SDK_UPGRADEFAIL = 52,
  NET_SDK_CARDHAVEINIT = 53,
  NET_SDK_PLAYERFAILED = 54,
  NET_SDK_MAX_USERNUM = 55,
  NET_SDK_GETLOCALIPANDMACFAIL = 56,
  NET_SDK_NOENCODEING = 57,
  NET_SDK_IPMISMATCH = 58,
  NET_SDK_MACMISMATCH = 59,
  NET_SDK_UPGRADELANGMISMATCH = 60,
  NET_SDK_MAX_PLAYERPORT = 61,
  NET_SDK_NOSPACEBACKUP = 62,
  NET_SDK_NODEVICEBACKUP = 63,
  NET_SDK_PICTURE_BITS_ERROR = 64,
  NET_SDK_PICTURE_DIMENSION_ERROR = 65,
  NET_SDK_PICTURE_SIZ_ERROR = 66,
  NET_SDK_LOADPLAYERSDKFAILED = 67,
  NET_SDK_LOADPLAYERSDKPROC_ERROR = 68,
  NET_SDK_LOADDSSDKFAILED = 69,
  NET_SDK_LOADDSSDKPROC_ERROR = 70,
  NET_SDK_DSSDK_ERROR = 71,
  NET_SDK_VOICEMONOPOLIZE = 72,
  NET_SDK_JOINMULTICASTFAILED = 73,
  NET_SDK_CREATEDIR_ERROR = 74,
  NET_SDK_BINDSOCKET_ERROR = 75,
  NET_SDK_SOCKETCLOSE_ERROR = 76,
  NET_SDK_USERID_ISUSING = 77,
  NET_SDK_PROGRAM_EXCEPTION = 78,
  NET_SDK_WRITEFILE_FAILED = 79,
  NET_SDK_FORMAT_READONLY = 80,
  NET_SDK_WITHSAMEUSERNAME = 81,
  NET_SDK_DEVICETYPE_ERROR = 82,
  NET_SDK_LANGUAGE_ERROR = 83,
  NET_SDK_PARAVERSION_ERROR = 84,
  NET_SDK_FILE_SUCCESS = 85,
  NET_SDK_FILE_NOFIND = 86,
  NET_SDK_NOMOREFILE = 87,
  NET_SDK_FILE_EXCEPTION = 88,
  NET_SDK_TRY_LATER = 89,
  NET_SDK_DEVICE_OFFLINE = 90,
  NET_SDK_CREATEJPEGSTREAM_FAIL = 91,
  NET_SDK_USER_ERROR_NO_USER = 92,
  NET_SDK_USER_ERROR_USER_OR_PASSWORD_IS_NULL = 93,
  NET_SDK_USER_ERROR_ALREDAY_LOGIN = 94,
  NET_SDK_USER_ERROR_SYSTEM_BUSY = 95,
  NET_SDK_DEVICE_NOT_SUPPROT = 96,
  NET_SDK_USER_ERROR_SYSTEM_NO_READY = 97,
  NET_SDK_CHANNEL_OFFLINE = 98,
  NET_SDK_GETREADYINFO_FAIL = 99,
  NET_SDK_NORESOURCE = 100,
  NET_SDK_DEVICE_QUERYSYSTEMCAPS_FAIL = 101,
  NET_SDK_INBUFFER_TOSMALL = 102,
  NET_SDK_NO_PASSWORD_STRENGTH = 103,
  NET_SDK_FILE_NOT_MATCH_PRODUCT = 104
}
// spell-checker: enable

export type DeviceInfo = {
  localVideoInputNum: number
  audioInputNum: number
  sensorInputNum: number
  sensorOutputNum: number
  displayResolutionMask: number
  // spell-checker: disable-next-line
  videoOuputNum: number
  netVideoOutputNum: number
  netVideoInputNum: number
  IVSNum: number
  presetNumOneCH: number
  cruiseNumOneCH: number
  presetNumOneCruise: number
  trackNumOneCH: number
  userNum: number
  netClientNum: number
  netFirstStreamNum: number
  deviceType: number
  // spell-checker: disable-next-line
  doblueStream: number
  audioStream: number
  talkAudio: number
  bPasswordCheck: number
  defBrightness: number
  defContrast: number
  defSaturation: number
  defHue: number
  videoInputNum: number
  deviceID: number
  videoFormat: number
  function: Uint32Array
  deviceIP: number
  deviceMAC: Uint8Array
  devicePort: number
  buildDate: number
  buildTime: number
  deviceName: string
  firmwareVersion: string
  kernelVersion: string
  hardwareVersion: string
  MCUVersion: string
  firmwareVersionEx: string
  softwareVer: number
  szSN: string
  deviceProduct: string
}
